[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # Unite.vimが依存（↓ではbuildできないから手動でmakeした）
repo = 'Shougo/vimproc.vim'
# build = 'make' # 失敗
# hook_post_source = '''
#   call dein#add('Shougo/vimproc.vim', {'build': 'make'}) # 失敗
# '''

[[plugins]] # vimfilerが依存
repo   = 'Shougo/unite.vim'

[[plugins]] # VSCodeっぽいファイラ（後継としてdefx.nvimが開発中）
repo = 'Shougo/vimfiler'

# [[plugins]] # Unite.vimの後継（vimfilerの依存として使えないから保留。将来的にdenite.nvim+defx.nvimの組み合わせにする予定）
# repo = 'Shougo/denite.nvim'
# # プラグインが読み込まれた直後に実行
# hook_post_source = '''
#   call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
#   call denite#custom#var('grep', 'command', ['ag'])
#   call denite#custom#var('grep', 'recursive_opts', [])
#   call denite#custom#var('grep', 'pattern_opt', [])
#   call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
# '''